<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/estilos.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js"></script>
        <title>Hoteles</title>    
    </head>
    <body>
        <h1>Hoteles</h1>
        <nav class="nav">
            <a class="nav-link active" href="index.php">Inicio</a></li>
            <a class="nav-link" href="nuevo_hotel.php">Nuevo hotel</a></li>
         </nav>
